package middleware

import (
	"net/http"
	"regexp"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestRequestID_WithClientProvidedID(t *testing.T) {
	clientID := "0196a3b2c4d50000a1b2c3d4e5f67890"
	c, w := buildTestRequest(http.MethodGet, "/test", map[string]string{
		"X-Request-ID": clientID,
	}, nil)

	middleware := RequestID()
	middleware(c)

	requestID, exists := c.Get("request_id")
	assert.True(t, exists)
	assert.Equal(t, clientID, requestID)
	assert.Equal(t, clientID, w.Header().Get("X-Request-ID"))
}

func TestRequestID_AutoGenerated(t *testing.T) {
	c, w := buildTestRequest(http.MethodGet, "/test", nil, nil)

	middleware := RequestID()
	middleware(c)

	requestID, exists := c.Get("request_id")
	assert.True(t, exists)
	requestIDStr := requestID.(string)
	assert.Len(t, requestIDStr, 32)
	assert.Equal(t, requestIDStr, w.Header().Get("X-Request-ID"))
}

func TestRequestID_EmptyClientProvidedID(t *testing.T) {
	c, w := buildTestRequest(http.MethodGet, "/test", map[string]string{
		"X-Request-ID": "",
	}, nil)

	middleware := RequestID()
	middleware(c)

	requestID, exists := c.Get("request_id")
	assert.True(t, exists)
	requestIDStr := requestID.(string)
	assert.Len(t, requestIDStr, 32)
	assert.Equal(t, requestIDStr, w.Header().Get("X-Request-ID"))
}

func TestRequestID_GeneratedIDFormat(t *testing.T) {
	c, _ := buildTestRequest(http.MethodGet, "/test", nil, nil)

	middleware := RequestID()
	middleware(c)

	requestID, _ := c.Get("request_id")
	requestIDStr := requestID.(string)
	matched, _ := regexp.MatchString("^[0-9a-f]{32}$", requestIDStr)
	assert.True(t, matched, "生成的 ID 应该是 32 位小写十六进制字符")
}

func TestRequestID_ResponseHeaderContainsID(t *testing.T) {
	c, w := buildTestRequest(http.MethodGet, "/test", nil, nil)

	middleware := RequestID()
	middleware(c)

	assert.NotEmpty(t, w.Header().Get("X-Request-ID"))
}

func TestRequestID_ContextAndHeaderConsistency(t *testing.T) {
	c, w := buildTestRequest(http.MethodGet, "/test", nil, nil)

	middleware := RequestID()
	middleware(c)

	contextID, _ := c.Get("request_id")
	headerID := w.Header().Get("X-Request-ID")
	assert.Equal(t, contextID, headerID)
}

func TestRequestID_UniquePerRequest(t *testing.T) {
	c1, _ := buildTestRequest(http.MethodGet, "/test", nil, nil)
	RequestID()(c1)

	c2, _ := buildTestRequest(http.MethodGet, "/test", nil, nil)
	RequestID()(c2)

	id1, _ := c1.Get("request_id")
	id2, _ := c2.Get("request_id")
	assert.NotEqual(t, id1, id2)
}

func TestRequestID_PassThroughNonStandardFormat(t *testing.T) {
	customID := "my-custom-id-123"
	c, w := buildTestRequest(http.MethodGet, "/test", map[string]string{
		"X-Request-ID": customID,
	}, nil)

	middleware := RequestID()
	middleware(c)

	requestID, exists := c.Get("request_id")
	assert.True(t, exists)
	assert.Equal(t, customID, requestID)
	assert.Equal(t, customID, w.Header().Get("X-Request-ID"))
}
