// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q             = new(Query)
	Channel       *channel
	Message       *message
	RefreshToken  *refreshToken
	Source        *source
	SourceChannel *sourceChannel
	User          *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Channel = &Q.Channel
	Message = &Q.Message
	RefreshToken = &Q.RefreshToken
	Source = &Q.Source
	SourceChannel = &Q.SourceChannel
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:            db,
		Channel:       newChannel(db, opts...),
		Message:       newMessage(db, opts...),
		RefreshToken:  newRefreshToken(db, opts...),
		Source:        newSource(db, opts...),
		SourceChannel: newSourceChannel(db, opts...),
		User:          newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Channel       channel
	Message       message
	RefreshToken  refreshToken
	Source        source
	SourceChannel sourceChannel
	User          user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		Channel:       q.Channel.clone(db),
		Message:       q.Message.clone(db),
		RefreshToken:  q.RefreshToken.clone(db),
		Source:        q.Source.clone(db),
		SourceChannel: q.SourceChannel.clone(db),
		User:          q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		Channel:       q.Channel.replaceDB(db),
		Message:       q.Message.replaceDB(db),
		RefreshToken:  q.RefreshToken.replaceDB(db),
		Source:        q.Source.replaceDB(db),
		SourceChannel: q.SourceChannel.replaceDB(db),
		User:          q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Channel       IChannelDo
	Message       IMessageDo
	RefreshToken  IRefreshTokenDo
	Source        ISourceDo
	SourceChannel ISourceChannelDo
	User          IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Channel:       q.Channel.WithContext(ctx),
		Message:       q.Message.WithContext(ctx),
		RefreshToken:  q.RefreshToken.WithContext(ctx),
		Source:        q.Source.WithContext(ctx),
		SourceChannel: q.SourceChannel.WithContext(ctx),
		User:          q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
