// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"octotify/internal/model"
)

func newSourceChannel(db *gorm.DB, opts ...gen.DOOption) sourceChannel {
	_sourceChannel := sourceChannel{}

	_sourceChannel.sourceChannelDo.UseDB(db, opts...)
	_sourceChannel.sourceChannelDo.UseModel(&model.SourceChannel{})

	tableName := _sourceChannel.sourceChannelDo.TableName()
	_sourceChannel.ALL = field.NewAsterisk(tableName)
	_sourceChannel.SourceID = field.NewInt64(tableName, "source_id")
	_sourceChannel.ChannelID = field.NewInt64(tableName, "channel_id")
	_sourceChannel.Status = field.NewInt(tableName, "status")
	_sourceChannel.CreatedAt = field.NewTime(tableName, "created_at")

	_sourceChannel.fillFieldMap()

	return _sourceChannel
}

type sourceChannel struct {
	sourceChannelDo

	ALL       field.Asterisk
	SourceID  field.Int64
	ChannelID field.Int64
	Status    field.Int
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (s sourceChannel) Table(newTableName string) *sourceChannel {
	s.sourceChannelDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sourceChannel) As(alias string) *sourceChannel {
	s.sourceChannelDo.DO = *(s.sourceChannelDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sourceChannel) updateTableName(table string) *sourceChannel {
	s.ALL = field.NewAsterisk(table)
	s.SourceID = field.NewInt64(table, "source_id")
	s.ChannelID = field.NewInt64(table, "channel_id")
	s.Status = field.NewInt(table, "status")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *sourceChannel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sourceChannel) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 4)
	s.fieldMap["source_id"] = s.SourceID
	s.fieldMap["channel_id"] = s.ChannelID
	s.fieldMap["status"] = s.Status
	s.fieldMap["created_at"] = s.CreatedAt
}

func (s sourceChannel) clone(db *gorm.DB) sourceChannel {
	s.sourceChannelDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sourceChannel) replaceDB(db *gorm.DB) sourceChannel {
	s.sourceChannelDo.ReplaceDB(db)
	return s
}

type sourceChannelDo struct{ gen.DO }

type ISourceChannelDo interface {
	gen.SubQuery
	Debug() ISourceChannelDo
	WithContext(ctx context.Context) ISourceChannelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISourceChannelDo
	WriteDB() ISourceChannelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISourceChannelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISourceChannelDo
	Not(conds ...gen.Condition) ISourceChannelDo
	Or(conds ...gen.Condition) ISourceChannelDo
	Select(conds ...field.Expr) ISourceChannelDo
	Where(conds ...gen.Condition) ISourceChannelDo
	Order(conds ...field.Expr) ISourceChannelDo
	Distinct(cols ...field.Expr) ISourceChannelDo
	Omit(cols ...field.Expr) ISourceChannelDo
	Join(table schema.Tabler, on ...field.Expr) ISourceChannelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISourceChannelDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISourceChannelDo
	Group(cols ...field.Expr) ISourceChannelDo
	Having(conds ...gen.Condition) ISourceChannelDo
	Limit(limit int) ISourceChannelDo
	Offset(offset int) ISourceChannelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISourceChannelDo
	Unscoped() ISourceChannelDo
	Create(values ...*model.SourceChannel) error
	CreateInBatches(values []*model.SourceChannel, batchSize int) error
	Save(values ...*model.SourceChannel) error
	First() (*model.SourceChannel, error)
	Take() (*model.SourceChannel, error)
	Last() (*model.SourceChannel, error)
	Find() ([]*model.SourceChannel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SourceChannel, err error)
	FindInBatches(result *[]*model.SourceChannel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SourceChannel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISourceChannelDo
	Assign(attrs ...field.AssignExpr) ISourceChannelDo
	Joins(fields ...field.RelationField) ISourceChannelDo
	Preload(fields ...field.RelationField) ISourceChannelDo
	FirstOrInit() (*model.SourceChannel, error)
	FirstOrCreate() (*model.SourceChannel, error)
	FindByPage(offset int, limit int) (result []*model.SourceChannel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISourceChannelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sourceChannelDo) Debug() ISourceChannelDo {
	return s.withDO(s.DO.Debug())
}

func (s sourceChannelDo) WithContext(ctx context.Context) ISourceChannelDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sourceChannelDo) ReadDB() ISourceChannelDo {
	return s.Clauses(dbresolver.Read)
}

func (s sourceChannelDo) WriteDB() ISourceChannelDo {
	return s.Clauses(dbresolver.Write)
}

func (s sourceChannelDo) Session(config *gorm.Session) ISourceChannelDo {
	return s.withDO(s.DO.Session(config))
}

func (s sourceChannelDo) Clauses(conds ...clause.Expression) ISourceChannelDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sourceChannelDo) Returning(value interface{}, columns ...string) ISourceChannelDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sourceChannelDo) Not(conds ...gen.Condition) ISourceChannelDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sourceChannelDo) Or(conds ...gen.Condition) ISourceChannelDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sourceChannelDo) Select(conds ...field.Expr) ISourceChannelDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sourceChannelDo) Where(conds ...gen.Condition) ISourceChannelDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sourceChannelDo) Order(conds ...field.Expr) ISourceChannelDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sourceChannelDo) Distinct(cols ...field.Expr) ISourceChannelDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sourceChannelDo) Omit(cols ...field.Expr) ISourceChannelDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sourceChannelDo) Join(table schema.Tabler, on ...field.Expr) ISourceChannelDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sourceChannelDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISourceChannelDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sourceChannelDo) RightJoin(table schema.Tabler, on ...field.Expr) ISourceChannelDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sourceChannelDo) Group(cols ...field.Expr) ISourceChannelDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sourceChannelDo) Having(conds ...gen.Condition) ISourceChannelDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sourceChannelDo) Limit(limit int) ISourceChannelDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sourceChannelDo) Offset(offset int) ISourceChannelDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sourceChannelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISourceChannelDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sourceChannelDo) Unscoped() ISourceChannelDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sourceChannelDo) Create(values ...*model.SourceChannel) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sourceChannelDo) CreateInBatches(values []*model.SourceChannel, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sourceChannelDo) Save(values ...*model.SourceChannel) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sourceChannelDo) First() (*model.SourceChannel, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SourceChannel), nil
	}
}

func (s sourceChannelDo) Take() (*model.SourceChannel, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SourceChannel), nil
	}
}

func (s sourceChannelDo) Last() (*model.SourceChannel, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SourceChannel), nil
	}
}

func (s sourceChannelDo) Find() ([]*model.SourceChannel, error) {
	result, err := s.DO.Find()
	return result.([]*model.SourceChannel), err
}

func (s sourceChannelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SourceChannel, err error) {
	buf := make([]*model.SourceChannel, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sourceChannelDo) FindInBatches(result *[]*model.SourceChannel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sourceChannelDo) Attrs(attrs ...field.AssignExpr) ISourceChannelDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sourceChannelDo) Assign(attrs ...field.AssignExpr) ISourceChannelDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sourceChannelDo) Joins(fields ...field.RelationField) ISourceChannelDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sourceChannelDo) Preload(fields ...field.RelationField) ISourceChannelDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sourceChannelDo) FirstOrInit() (*model.SourceChannel, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SourceChannel), nil
	}
}

func (s sourceChannelDo) FirstOrCreate() (*model.SourceChannel, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SourceChannel), nil
	}
}

func (s sourceChannelDo) FindByPage(offset int, limit int) (result []*model.SourceChannel, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sourceChannelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sourceChannelDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sourceChannelDo) Delete(models ...*model.SourceChannel) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sourceChannelDo) withDO(do gen.Dao) *sourceChannelDo {
	s.DO = *do.(*gen.DO)
	return s
}
